### ISSUE TITLE
Rename-restructure the project-module

### ISSUE THREAD

**Issue by augustocristian** [giis-uniovi/retorch-llm-rp#2]
After the comment of Javier: https://github.com/giis-uniovi/retorch-llm-rp/pull/1#discussion_r1761409557 
I think it would be a good idea to keep the repository-project name and rename the module to `retorch-rp-expstudy`. This change would help us differentiate between the current RP and any future RPs that may be added for other research lines.

**Comment by javiertuya** [comment]
@augustocristian Better `retorch-llm-rp-expstudy` or `llm-rp-expstudy`
